// <auto-generated />
using System;
using CariProjesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CariProje.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828132420__Added_AccountName_Filed_To_Movements_")]
    partial class _Added_AccountName_Filed_To_Movements_
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CariProjesi.Models.Account", b =>
                {
                    b.Property<string>("AccountCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountCountry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccountCredit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccountDebit")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountDistrict")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountSurname")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountCode");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CariProjesi.Models.Movement", b =>
                {
                    b.Property<Guid>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MovementChange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MovementType")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovementId");

                    b.HasIndex("AccountCode");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("CariProjesi.Models.Movement", b =>
                {
                    b.HasOne("CariProjesi.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountCode");
                });
#pragma warning restore 612, 618
        }
    }
}
